name: Node Continuous Integration

on:
  push: 
    branches: [main]
  
jobs: 
  test_push: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      # can add test command here if needed, e.g. npm test
      - run: npm run build